development:
 facility_name: Kamuzu Central Hospital
 facility_code: KCH
 district: Lilongwe
 central_repo: http://localhost:3004
 national-repo-node: http://localhost:3014
 national_dashboard: http://localhost:3005
production:
 facility_name: Kamuzu Central Hospital
 facility_code: KCH
 district: Lilongwe
 central_repo: http://localhost:3004
 national-repo-node: http://localhost:3014
 national_dashboard: http://localhost:3005
