development:
  dde_url: http://192.168.6.211:3009
  application_name: lims_order_entry
  site_code: kch
  dde_default_username: admin
  dde_default_password: admin
  dde_application_username: lims_order_entry
  dde_application_password: lims_order_entry

test:
  <<: *development

production:
  <<: *development

