default: &default
    dde_url: http://10.5.50.220:3009
    application_name: lims_order_entry
    site_code: kch
    dde_default_username: test10
    dde_default_password: test10
    dde_application_username: test30
    dde_application_password: test30

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

