default: &default
    dde_url: http://192.168.6.203:3009
    application_name: lims_order_entry
    site_code: kch
    dde_default_username: test10
    dde_default_password: test10
    dde_application_username: order_entry
    dde_application_password: order_entry

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default

